[package]
name = "wgpu_text"
authors = ["Leon (Blatko1)"]
version = "0.1.3"
edition = "2021"
description = "Simple library for rendering text with wgpu"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Blatko1/wgpu-text"
keywords = ["wgpu", "text", "ttf", "truetype", "font"]
categories = ["graphics", "rendering"]
resolver = "2"

[dependencies]
wgpu = "0.12.0"
glyph_brush = "0.7.3"
log = "0.4.14"

[dependencies.bytemuck]
version = "1.8"
features = ["derive"]

[dev-dependencies]
winit = "0.26.1"
pollster = "0.2.5"
env_logger = "0.9.0"
log = "0.4.14"
rand = "0.8.5"