[package]
name = "wgpu_text"
authors = ["Leon (Blatko1)"]
version = "0.6.6"
edition = "2021"
description = "A simple 2D text renderer for wgpu"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Blatko1/wgpu-text"
keywords = ["wgpu", "text", "ttf", "truetype", "font"]
categories = ["graphics", "rendering"]
resolver = "2"
include = ["src/**/*", "LICENSE", "Cargo.toml", "README.md", ".gitignore"]

[dependencies]
wgpu = "0.15.1"
glyph_brush = "0.7.6"
log = "0.4.17"
bytemuck = { version = "1.13.0", features = ["derive"]}

[dev-dependencies]
winit = "0.28.1"
pollster = "0.3.0"
env_logger = "0.10.0"
rand = "0.8.5"
