[package]
name = "wgpu_text"
authors = ["Leon (Blatko1)"]
version = "0.6.7"
edition = "2021"
description = "A simple 2D text renderer for wgpu"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Blatko1/wgpu-text"
keywords = ["wgpu", "text", "ttf", "render", "font"]
categories = ["graphics", "rendering"]
resolver = "2"
include = ["src/**/*", "LICENSE", "Cargo.toml", "README.md", ".gitignore"]

[dependencies]
wgpu = "0.15.1"
glyph_brush = "0.7.7"
log = "0.4.17"
bytemuck = { version = "1.13.1", features = ["derive"] }

[dev-dependencies]
wgpu = { version = "0.15.1", features = ["spirv"] }
winit = "0.28.3"
pollster = "0.3.0"
env_logger = "0.10.0"
rand = "0.8.5"
nalgebra = "0.32.2"

[[example]]
path = "examples/custom_surface/custom_surface.rs"
name = "custom_surface"
